spring.application.name=farmacia_autenticacao

spring.datasource.url=jdbc:mysql://localhost:3307/farmacia
spring.datasource.username=farmacia
spring.datasource.password=farmacia

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CREATE TABLE usuarios(     id BIGINT NOT NULL AUTO_INCREMENT,     nome VARCHAR(100) NOT NULL,     email VARCHAR(100) NOT NULL UNIQUE,     senha VARCHAR(100) NOT NULL,      PRIMARY KEY(id) );
# INSERT INTO usuarios(nome, email, senha) VALUES ('teste', 'teste@', '123');
# update usuarios set senha = "$2a$12$ifiw1S13lsaN/1sXWmdaW.cdfIHYucdEuveJnPa8s8inaVzilFpaq" where id = 2;