services:
  mysql:
    image: mysql:8.4
    container_name: farmacia-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: farmacia
      MYSQL_USER: farmacia
      MYSQL_PASSWORD: farmacia
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
